"""Create tables for search service

Revision ID: 8174b18d81f1
Revises: 
Create Date: 2025-05-05 19:48:03.267994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8174b18d81f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_search',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('last_searched_at', sa.DateTime(), nullable=True),
    sa.Column('daily_count', sa.Integer(), nullable=True),
    sa.Column('weekly_count', sa.Integer(), nullable=True),
    sa.Column('monthly_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='search_service_schema'
    )
    op.create_index(op.f('ix_search_service_schema_popular_search_count'), 'popular_search', ['count'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_popular_search_id'), 'popular_search', ['id'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_popular_search_query_text'), 'popular_search', ['query_text'], unique=True, schema='search_service_schema')
    op.create_table('search_index',
    sa.Column('index_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tag_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interest_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('added_by_username', sa.String(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('index_id'),
    schema='search_service_schema'
    )
    op.create_index(op.f('ix_search_service_schema_search_index_added_date'), 'search_index', ['added_date'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_avg_rating'), 'search_index', ['avg_rating'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_content_type'), 'search_index', ['content_type'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_index_id'), 'search_index', ['index_id'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_is_recommended'), 'search_index', ['is_recommended'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_is_verified'), 'search_index', ['is_verified'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_popularity_score'), 'search_index', ['popularity_score'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_publication_date'), 'search_index', ['publication_date'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_source_id'), 'search_index', ['source_id'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_index_title'), 'search_index', ['title'], unique=False, schema='search_service_schema')
    op.create_table('search_query',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('query_id'),
    schema='search_service_schema'
    )
    op.create_index(op.f('ix_search_service_schema_search_query_created_at'), 'search_query', ['created_at'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_query_query_id'), 'search_query', ['query_id'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_query_query_text'), 'search_query', ['query_text'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_query_user_id'), 'search_query', ['user_id'], unique=False, schema='search_service_schema')
    op.create_table('search_suggestion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='search_service_schema'
    )
    op.create_index(op.f('ix_search_service_schema_search_suggestion_id'), 'search_suggestion', ['id'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_suggestion_text'), 'search_suggestion', ['text'], unique=True, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_suggestion_type'), 'search_suggestion', ['type'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_search_suggestion_weight'), 'search_suggestion', ['weight'], unique=False, schema='search_service_schema')
    op.create_table('user_recent_search',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='search_service_schema'
    )
    op.create_index(op.f('ix_search_service_schema_user_recent_search_created_at'), 'user_recent_search', ['created_at'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_user_recent_search_id'), 'user_recent_search', ['id'], unique=False, schema='search_service_schema')
    op.create_index(op.f('ix_search_service_schema_user_recent_search_user_id'), 'user_recent_search', ['user_id'], unique=False, schema='search_service_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_service_schema_user_recent_search_user_id'), table_name='user_recent_search', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_user_recent_search_id'), table_name='user_recent_search', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_user_recent_search_created_at'), table_name='user_recent_search', schema='search_service_schema')
    op.drop_table('user_recent_search', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_suggestion_weight'), table_name='search_suggestion', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_suggestion_type'), table_name='search_suggestion', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_suggestion_text'), table_name='search_suggestion', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_suggestion_id'), table_name='search_suggestion', schema='search_service_schema')
    op.drop_table('search_suggestion', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_query_user_id'), table_name='search_query', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_query_query_text'), table_name='search_query', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_query_query_id'), table_name='search_query', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_query_created_at'), table_name='search_query', schema='search_service_schema')
    op.drop_table('search_query', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_title'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_source_id'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_publication_date'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_popularity_score'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_is_verified'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_is_recommended'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_index_id'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_content_type'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_avg_rating'), table_name='search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_search_index_added_date'), table_name='search_index', schema='search_service_schema')
    op.drop_table('search_index', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_popular_search_query_text'), table_name='popular_search', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_popular_search_id'), table_name='popular_search', schema='search_service_schema')
    op.drop_index(op.f('ix_search_service_schema_popular_search_count'), table_name='popular_search', schema='search_service_schema')
    op.drop_table('popular_search', schema='search_service_schema')
    # ### end Alembic commands ###
