"""Create tables for recommendation service

Revision ID: 23abae52aff1
Revises: 
Create Date: 2025-05-05 19:33:12.163005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23abae52aff1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_recommendations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('recommendation_id'),
    schema='recommendation_service_schema'
    )
    op.create_index(op.f('ix_recommendation_service_schema_interest_recommendations_recommendation_id'), 'interest_recommendations', ['recommendation_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_interest_recommendations_source_id'), 'interest_recommendations', ['source_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_interest_recommendations_interest_id'), 'interest_recommendations', ['interest_id'], unique=False, schema='recommendation_service_schema')
    op.create_table('popular_sources',
    sa.Column('popular_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('save_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('time_period', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('popular_id'),
    schema='recommendation_service_schema'
    )
    op.create_index(op.f('ix_recommendation_service_schema_popular_sources_popular_id'), 'popular_sources', ['popular_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_popular_sources_source_id'), 'popular_sources', ['source_id'], unique=False, schema='recommendation_service_schema')
    op.create_table('similar_sources',
    sa.Column('similar_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('similar_source_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('similarity_reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('similar_id'),
    schema='recommendation_service_schema'
    )
    op.create_index(op.f('ix_recommendation_service_schema_similar_sources_similar_source_id'), 'similar_sources', ['similar_source_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_similar_sources_similar_id'), 'similar_sources', ['similar_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_similar_sources_source_id'), 'similar_sources', ['source_id'], unique=False, schema='recommendation_service_schema')
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('liked_sources', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('disliked_sources', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('viewed_sources', sa.JSON(), nullable=True),
    sa.Column('interest_weights', sa.JSON(), nullable=True),
    sa.Column('content_type_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('preference_id'),
    schema='recommendation_service_schema'
    )
    op.create_index(op.f('ix_recommendation_service_schema_user_preferences_preference_id'), 'user_preferences', ['preference_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False, schema='recommendation_service_schema')
    op.create_table('user_recommendations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=255), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_shown', sa.Integer(), nullable=True),
    sa.Column('is_clicked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('recommendation_id'),
    schema='recommendation_service_schema'
    )
    op.create_index(op.f('ix_recommendation_service_schema_user_recommendations_recommendation_id'), 'user_recommendations', ['recommendation_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_user_recommendations_source_id'), 'user_recommendations', ['source_id'], unique=False, schema='recommendation_service_schema')
    op.create_index(op.f('ix_recommendation_service_schema_user_recommendations_user_id'), 'user_recommendations', ['user_id'], unique=False, schema='recommendation_service_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_service_schema_user_recommendations_user_id'), table_name='user_recommendations', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_user_recommendations_source_id'), table_name='user_recommendations', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_user_recommendations_recommendation_id'), table_name='user_recommendations', schema='recommendation_service_schema')
    op.drop_table('user_recommendations', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_user_preferences_user_id'), table_name='user_preferences', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_user_preferences_preference_id'), table_name='user_preferences', schema='recommendation_service_schema')
    op.drop_table('user_preferences', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_similar_sources_source_id'), table_name='similar_sources', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_similar_sources_similar_id'), table_name='similar_sources', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_similar_sources_similar_source_id'), table_name='similar_sources', schema='recommendation_service_schema')
    op.drop_table('similar_sources', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_popular_sources_source_id'), table_name='popular_sources', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_popular_sources_popular_id'), table_name='popular_sources', schema='recommendation_service_schema')
    op.drop_table('popular_sources', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_interest_recommendations_interest_id'), table_name='interest_recommendations', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_interest_recommendations_source_id'), table_name='interest_recommendations', schema='recommendation_service_schema')
    op.drop_index(op.f('ix_recommendation_service_schema_interest_recommendations_recommendation_id'), table_name='interest_recommendations', schema='recommendation_service_schema')
    op.drop_table('interest_recommendations', schema='recommendation_service_schema')
    # ### end Alembic commands ###
