"""Create tables for collection service

Revision ID: c86c4b320458
Revises: 
Create Date: 2025-05-05 19:57:15.810685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86c4b320458'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('collection_id'),
    schema='collection_service_schema'
    )
    op.create_index(op.f('ix_collection_service_schema_collection_collection_id'), 'collection', ['collection_id'], unique=False, schema='collection_service_schema')
    op.create_table('collection_source',
    sa.Column('collection_source_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection_service_schema.collection.collection_id'], ),
    sa.PrimaryKeyConstraint('collection_source_id'),
    schema='collection_service_schema'
    )
    op.create_index(op.f('ix_collection_service_schema_collection_source_collection_source_id'), 'collection_source', ['collection_source_id'], unique=False, schema='collection_service_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_service_schema_collection_source_collection_source_id'), table_name='collection_source', schema='collection_service_schema')
    op.drop_table('collection_source', schema='collection_service_schema')
    op.drop_index(op.f('ix_collection_service_schema_collection_collection_id'), table_name='collection', schema='collection_service_schema')
    op.drop_table('collection', schema='collection_service_schema')
    # ### end Alembic commands ###
