"""Create tables for admin service

Revision ID: 25660fee7a0c
Revises: 
Create Date: 2025-05-05 18:42:56.640600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25660fee7a0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('complaint_id'),
    schema='admin_service_schema'
    )
    op.create_index(op.f('ix_admin_service_schema_complaint_complaint_id'), 'complaint', ['complaint_id'], unique=False, schema='admin_service_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_service_schema_complaint_complaint_id'), table_name='complaint', schema='admin_service_schema')
    op.drop_table('complaint', schema='admin_service_schema')
    # ### end Alembic commands ###
