"""Create tables for content service

Revision ID: 952659e7cedc
Revises: 
Create Date: 2025-05-05 20:07:58.208980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952659e7cedc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('source_id'),
    schema='content_service_schema'
    )
    op.create_index(op.f('ix_content_service_schema_source_source_id'), 'source', ['source_id'], unique=False, schema='content_service_schema')
    op.create_index(op.f('ix_content_service_schema_source_title'), 'source', ['title'], unique=False, schema='content_service_schema')
    op.create_table('tag',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    schema='content_service_schema'
    )
    op.create_index(op.f('ix_content_service_schema_tag_name'), 'tag', ['name'], unique=True, schema='content_service_schema')
    op.create_index(op.f('ix_content_service_schema_tag_tag_id'), 'tag', ['tag_id'], unique=False, schema='content_service_schema')
    op.create_table('rating',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['content_service_schema.source.source_id'], ),
    sa.PrimaryKeyConstraint('rating_id'),
    schema='content_service_schema'
    )
    op.create_index(op.f('ix_content_service_schema_rating_rating_id'), 'rating', ['rating_id'], unique=False, schema='content_service_schema')
    op.create_table('source_tag',
    sa.Column('source_tag_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_service_schema.source.source_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['content_service_schema.tag.tag_id'], ),
    sa.PrimaryKeyConstraint('source_tag_id'),
    schema='content_service_schema'
    )
    op.create_index(op.f('ix_content_service_schema_source_tag_source_tag_id'), 'source_tag', ['source_tag_id'], unique=False, schema='content_service_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_service_schema_source_tag_source_tag_id'), table_name='source_tag', schema='content_service_schema')
    op.drop_table('source_tag', schema='content_service_schema')
    op.drop_index(op.f('ix_content_service_schema_rating_rating_id'), table_name='rating', schema='content_service_schema')
    op.drop_table('rating', schema='content_service_schema')
    op.drop_index(op.f('ix_content_service_schema_tag_tag_id'), table_name='tag', schema='content_service_schema')
    op.drop_index(op.f('ix_content_service_schema_tag_name'), table_name='tag', schema='content_service_schema')
    op.drop_table('tag', schema='content_service_schema')
    op.drop_index(op.f('ix_content_service_schema_source_title'), table_name='source', schema='content_service_schema')
    op.drop_index(op.f('ix_content_service_schema_source_source_id'), table_name='source', schema='content_service_schema')
    op.drop_table('source', schema='content_service_schema')
    # ### end Alembic commands ###
