"""Create tables for auth service

Revision ID: 083cc469c880
Revises: 
Create Date: 2025-05-05 16:22:32.921988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083cc469c880'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='auth_service_schema'
    )
    op.create_index(op.f('ix_auth_service_schema_user_auth_email'), 'user_auth', ['email'], unique=True, schema='auth_service_schema')
    op.create_index(op.f('ix_auth_service_schema_user_auth_user_id'), 'user_auth', ['user_id'], unique=False, schema='auth_service_schema')
    op.create_index(op.f('ix_auth_service_schema_user_auth_username'), 'user_auth', ['username'], unique=False, schema='auth_service_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_service_schema_user_auth_username'), table_name='user_auth', schema='auth_service_schema')
    op.drop_index(op.f('ix_auth_service_schema_user_auth_user_id'), table_name='user_auth', schema='auth_service_schema')
    op.drop_index(op.f('ix_auth_service_schema_user_auth_email'), table_name='user_auth', schema='auth_service_schema')
    op.drop_table('user_auth', schema='auth_service_schema')
    # ### end Alembic commands ###
