"""Create tables for parser service

Revision ID: b941aa6c3c46
Revises: 
Create Date: 2025-05-05 20:32:23.767813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b941aa6c3c46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parser_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sources_found', sa.Integer(), nullable=True),
    sa.Column('sources_created', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    schema='parser_service_schema'
    )
    op.create_index(op.f('ix_parser_service_schema_parser_tasks_task_id'), 'parser_tasks', ['task_id'], unique=False, schema='parser_service_schema')
    op.create_table('parsed_sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source_site', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['parser_service_schema.parser_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('source_id'),
    schema='parser_service_schema'
    )
    op.create_index(op.f('ix_parser_service_schema_parsed_sources_source_id'), 'parsed_sources', ['source_id'], unique=False, schema='parser_service_schema')
    op.create_index(op.f('ix_parser_service_schema_parsed_sources_url'), 'parsed_sources', ['url'], unique=True, schema='parser_service_schema')
    op.create_table('scheduled_parser_tasks',
    sa.Column('scheduled_task_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_value', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['parser_service_schema.parser_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('scheduled_task_id'),
    schema='parser_service_schema'
    )
    op.create_index(op.f('ix_parser_service_schema_scheduled_parser_tasks_scheduled_task_id'), 'scheduled_parser_tasks', ['scheduled_task_id'], unique=False, schema='parser_service_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parser_service_schema_scheduled_parser_tasks_scheduled_task_id'), table_name='scheduled_parser_tasks', schema='parser_service_schema')
    op.drop_table('scheduled_parser_tasks', schema='parser_service_schema')
    op.drop_index(op.f('ix_parser_service_schema_parsed_sources_url'), table_name='parsed_sources', schema='parser_service_schema')
    op.drop_index(op.f('ix_parser_service_schema_parsed_sources_source_id'), table_name='parsed_sources', schema='parser_service_schema')
    op.drop_table('parsed_sources', schema='parser_service_schema')
    op.drop_index(op.f('ix_parser_service_schema_parser_tasks_task_id'), table_name='parser_tasks', schema='parser_service_schema')
    op.drop_table('parser_tasks', schema='parser_service_schema')
    # ### end Alembic commands ###
